### ISSUE TITLE
Retain Suggestions When Typing

### ISSUE THREAD

**Issue by WilliamsJack** [j0rd1smit/obsidian-copilot-auto-completion#10]
Obsidian Copilot Auto Completion will reject the suggestion as soon as the user continues to type, even if their text matches the suggestion.

This is different to the behaviour of GitHub Copilot, which continues to provide the suggestion up until the user types something that doesn't match the suggestion.

Pressing escape or clicking away will still clear the suggestion and transition back to the idle state.

# Example
**GitHub Copilot**
![GitHub Copilot retains suggestions](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/30068301/7d7f2d40-ae3e-4b8b-a973-956455468c8b)

**Obsidian Copilot Auto Completion**
![Obsidian Copilot Retains Suggestions](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/30068301/1d71f487-95dd-4506-b275-1760c12dffa8)

I've already hacked together a working version of this feature, but if you think it's a good addition I can clean it up and make a PR.

**Comment by j0rd1smit** [comment]
This is indeed something on my wish list but I haven't had time. So I'm happy to hear what you propose and discuss to come to a nice solution :)
