### ISSUE TITLE
a problem in language recognition

### ISSUE THREAD

**Issue by happyZYM** [j0rd1smit/obsidian-copilot-auto-completion#18]
Some times language recognition doesn't work well(I tried it in Chinese), and I modified the prompt in the System Message to `Your answer must be in the same language as the text directly surrounding the <mask/> .` and it seems better

**Comment by j0rd1smit** [comment]
Does that work consistently? If you I might update the default system prompt for everybody.
(I typically write in English, so I don't have much experience with it myself).

**Comment by happyZYM** [comment]
> Does that work consistently? If you I might update the default system prompt for everybody. (I typically write in English, so I don't have much experience with it myself).

I tried for 10~15 times, despite the effects not being absolute, there is a clear impact.
