### ISSUE TITLE
the ANSWER contains unwanted text

### ISSUE THREAD

**Issue by happyZYM** [j0rd1smit/obsidian-copilot-auto-completion#19]
![屏幕截图 2023-12-22 132304](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/33191271/bd16b422-34c8-4257-9fb8-1c25e495b856)
It seems that when I just want to complete a just a part of the sentence, the ANSWER contains the whole sentence.
I tried to fix this problem with the following System Message but in vain:
```
Your job is to predict the most logical text that should be written at the location of the <mask/>.
Your answer can be either code, a single word, or multiple sentences. The ANSWER should be exactly the answer itself that can be placed at <mask/> and should not include the text directly surrounding the <mask/>, especially when you found that you do not need to write a whole sentence at <mask/>.
Your answer must be in the same language as the text directly surrounding the <mask/> .
Your response must have the following format:
THOUGHT: here you explain your reasoning of what could be at the location of <mask/>
ANSWER: here you write the text that should be at the location of <mask/>
```

**Comment by happyZYM** [comment]
Does it has something to do with the code that parses the ANSWER? Such as some problems when processing characters beyond ASCII.

**Comment by j0rd1smit** [comment]
This is a known issue. GPT-3.5 finds it very hard to perform this task, whereas GPT-4 can do it perfectly. To make it work for GPT-3.5, I added this [post-processor](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/blob/e0ad919c95e724693bc9cbd091e07903dc716502/src/prediction_services/post_processors/remove_overlap.ts#L6C5-L6C12) that removes overlap. However, I did assume an English-like language when implementing this. Therefore, it might be worth examining the post-processor's code. If you find something there that causes the issue, please let me know.
