### ISSUE TITLE
No autocompletion happening

### ISSUE THREAD

**Issue by svdoever** [j0rd1smit/obsidian-copilot-auto-completion#21]
Obsidian version 1.5.3 - uses a new editor as I understood.
Configured for Azure Open AI, connection test works.
No auto-completion is happening.

**Comment by j0rd1smit** [comment]
I'm having some trouble replicating the issue. I'm also on 1.5.3 for me it still works.
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/d9e4f592-f219-41a3-986a-2e2428a07e83)
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/1dbc1355-4de0-49b5-a7d3-e949b76d538b)

I just made a small patch (1.0.7) that now logs the underlying exception to the developer's console. Maybe that will give you a better understanding of your issue.
You can open the developer's console using (`cmd+ option + i` on Mac and `ctrl + shift + I for Windows`). This should show you something like this:
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/c11c706e-4c52-407f-b381-27b973a693eb)

**Comment by svdoever** [comment]
<img width="474" alt="image" src="https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/246842/30ca05c7-2161-479f-b531-68a6bed70174">

<img width="474" alt="image" src="https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/246842/93d0ffc8-9c21-49b9-9125-41d7b1b78522">

But no output at all in console window (I cleared it, then renamed my note):

<img width="547" alt="image" src="https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/246842/0ea1692e-bd17-4f54-bad0-563500feed09">

**Comment by svdoever** [comment]
Ah cool, that works! I connected hotkey CTRL-] to predict, and pressing that key starts the prediction process. 

By the way, if a type a space, then CTRL-], wait for the completion, and then do backspace instead of tab, I get the error below:

<img width="550" alt="image" src="https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/246842/0f5165dc-66bb-4dd8-bf4a-32e7720e3e46">
