### ISSUE TITLE
Option to disable COT and examples

### ISSUE THREAD

**Issue by xl0** [j0rd1smit/obsidian-copilot-auto-completion#32]
I'd love to see an option (under Advanced) to completely disable CoT and examples.

I feel that a simple masked insertion would be enough for most uses, or at least I'd like to try and see if works better or worse.

**Comment by j0rd1smit** [comment]
Yeah you can already totally do that by doing the following:
1. enable advanced mode.
2. Change the system prompt something like:
```
Your job is to predict the most logical text that should be written at the location of the <mask/>.
Your answer can be either code, a single word, or multiple sentences.
If the <mask/> is in the middle of a partial sentence, your answer should only be the 1 or 2 words fixes the sentence and not the entire sentence.
You are not allowed to have any overlapping text directly surrounding the <mask/>.  
Your answer must be in the same language as the text directly surrounding the <mask/>.
Your response must have the following format:
ANSWER: here, you write the text that should be at the location of <mask/>
```
3. Then remove all the few-shot examples by pressing the cross.

So feel free to try that out.
However, I prefer to keep CoT enabled since it gives generally more consistent results. If you are doing simple paragraph completion, you won't notice it. But in other contexts, it has a huge impact on slides full of examples of different failure modes.

**Comment by xl0** [comment]
Got you, thank you!

I think there is another issue I was seeing - when the GPT response ends with "$" (end of a one-line Latex formula), I see the '$' in the debug console, but it's not shown as part of the completion.

**Comment by j0rd1smit** [comment]
It might have something to do with the post processors. 
You can disable them in the settings as well.
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/c747d833-27dc-4cf6-959e-23a4aeb7eb0f)

**Comment by xl0** [comment]
I got you, thank you. It looks like it always removes the trailing $, even if it would close the latex block.

**Comment by j0rd1smit** [comment]
Do you have an example it test out?

**Comment by xl0** [comment]
Hmm, I thought I had it, but I can't reliably reproduce it any more. :/

**Comment by xl0** [comment]
Yep, let me close it.

No, I thought I saw cases when the model would reply with a closing '$' at the end of an open math expression, and the '$' was incorrectly removed. But I can't reproduce it now.
