### ISSUE TITLE
Feature: Support Ollama and/or setting custom OpenAI endpoint

### ISSUE THREAD

**Issue by sammcj** [j0rd1smit/obsidian-copilot-auto-completion#37]
This would be good to use with Ollama which has both a native API which provides things such as model listing etc... and an "Open"AI compatible API.

**Comment by localjo** [comment]
You can use it with Ollama already: https://github.com/j0rd1smit/obsidian-copilot-auto-completion/blob/master/docs/how-to/Ollama%20setup%20guide.md
