### ISSUE TITLE
feature request: refactor existing text

### ISSUE THREAD

**Issue by RensDimmendaal** [j0rd1smit/obsidian-copilot-auto-completion#4]
I love the plugin.

In my daily work I now notice the following friction:
When I've already written some text, but I would like some part of it to be rewritten in one way or another.

What I imagine:

1. user writes text
2. user selects part of the existing text
3. user opens the command window
4. user selects the "Copilot: refactor text"
5. user provides refactoring instructions (e.g. "make more formal/informal/verbose/succinct/add example/...)
6. LLM takes in the original text, and gets instructions to replace the selected text based on the instructions.
7. in the obsidian app the original text is replaced with the new text
8. user can use the original "undo" functionality to undo the suggestion.

Happy to provide additional clarification if needed, but I hope you see what I mean.

Keep up the great work!!!

**Comment by j0rd1smit** [comment]
Decided this will remain out of scope for this plugin
