### ISSUE TITLE
Compatibility with Outliner Plugin

### ISSUE THREAD

**Issue by torbenkeller** [j0rd1smit/obsidian-copilot-auto-completion#41]
I use the [Outlinier Plugin](https://github.com/vslinko/obsidian-outliner) to get a better user experience modifying lists. Unfortunately it also binds ⇥ to indent a bullet point one level more. Now when I want to accept the prediction in an unordered list with ⇥  the bullet point will move and the prediction stays unaccepted. Would be awesome if acception the prediction would get a higher precedence than moving the bullet point

**Comment by j0rd1smit** [comment]
We are both using something like:  
  
```javascript  
Prec.highest(  
    keymap.of([  
        {  
            key: "Tab",  
            run: ...  
        },  
    ]),  
),  
```

We are both binding the Tab key to our custom behavior and giving ourselves the highest priority. This creates a conflict.
Unfortunately, this is not something I can fix. 

However, you could adjust which plugin wins the race by changingt he loading order. You can change this order in the .obsidian/community-plugins.json. Try playing around with this and see if it fixes your problem.

**Comment by j0rd1smit** [comment]
I'm not sure why this is.
My code checks if it is in the suggested state. If not, it returns false, which means, according to the doc:
![Screenshot 2024-06-19 at 16 20 11](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/bd36d75b-f7e5-41b2-ab37-ad5fb59900dc)

So then it should go to the other plugins.
I'm not sure how they handle this.
So I don't think this can be fixed nicely.

However, you could try accepting the suggestion not with the tab, but when a suggestion is there, open the command pallet and search for the copilot accept command. This should be inserted. (Additionally, you can bind this to another hot key if you want.)
