### ISSUE TITLE
Cannot connect to the openai API. Please check your settings.

### ISSUE THREAD

**Issue by alberttra** [j0rd1smit/obsidian-copilot-auto-completion#5]
After entering API-Key and click on Test Connection: Notification with message: Cannot connect to the openai API. Please
check your settings. No Setting has been changed

![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/16648814/b3554d5a-193e-4968-8b96-78587b98a650)

**Comment by j0rd1smit** [comment]
If you update the plugin, you should now see better error messages, such as:

![Screenshot 2023-09-01 at 20 56 04](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/d03c6d7e-9760-4d7a-8993-c9c0c421949b)

![Screenshot 2023-09-01 at 20 56 42](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/d665ce52-74b8-49b7-85b1-60da54f89099)

![Screenshot 2023-09-01 at 20 58 24](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/22663455/38e07d96-9e38-4a0a-a829-88e81e7ff891)

I believe this should fix your issue. If not, feel free to raise it again.

**Comment by ronilaukkarinen** [comment]
I have the same problem. I literally have 0 usage (just purchased).

<img width="789" alt="image" src="https://github.com/user-attachments/assets/c3f0071a-5daa-4735-a137-5d34d25b8fb6">

**Comment by j0rd1smit** [comment]
I'm really sorry to hear that @ronilaukkarinen. All the plugin does here is display the error message in the response body from the OpenAI API request. So, since you are getting a 429 error message, the plugin seems to be doing its job. Maybe your API quota has not been processed yet since you said: 'just purchased'?
